# Generated by Django 3.2.13 on 2022-11-18 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_review_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
    ]
