# Generated by Django 3.2.13 on 2022-11-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221118_1413'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_lang',
            field=models.ManyToManyField(related_name='user_lang', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_genre',
            field=models.ManyToManyField(related_name='user_genre', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(related_name='user_movies', to='movies.Movie'),
        ),
    ]
